version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  websvr:
    build: ./app
    container_name: web4mongo
    restart: unless-stopped
    volumes:
      - ./app/src:/var/www/html
    ports:
      - 80:80
    links:
      - mongo
    depends_on:
      - mongo